### ISSUE TITLE
Remove Intel Version Number

### ISSUE THREAD

**Issue by sabasinger** [nasa-jpl/macos#2]
In makefile_all.sh and macos_f90/Make-Linux-x86_64.T, there are references to /opt/intel-14.0.0/.  This can be simplified to /opt/intel/ because the latter is a soft link to the latest version.  Also, "2023.1.0" in the same lines can be replaced by "latest", because there exists a softlink as well.  This will make it more cross-platform independant.

**Comment by lmarchen** [comment]
I believe that the installation of the Intel Compiler libraries in "marchen" and "macos1" is not standard. I believe Danny mixed old and newer version in a single folder with soft links. I will resolve this issues #1 and #2 together by setting bash global variables for intel setvars.sh  and  linx/intel64 lib paths. I will take a look at the installation of the oneapi alone and will determine a generalize form of the bash and Makefile setup with an additional update.

**Comment by lmarchen** [comment]
This issue can be close because resolution to issue #1 took care of this.
